version: '3.8'

services:
  uploader:
    container_name: uploader-dev
    build:
      context: .
    environment:
      - RUST_LOG=info
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
      - MQTT_USERNAME=
      - MQTT_PASSWORD=
      - MQTT_ROOT_TOPIC=image_uploader
      - SFTP_HOST=sftp
      - SFTP_PORT=22
      - SFTP_USER=test
      - SFTP_PASSWORD=test
      - SFTP_REMOTE_DIR=/uploads
      - SMB_TARGET_IP=192.168.1.10
      - SMB_SHARE_NAME=default_share
      - SMB_TARGET_FOLDER=/upload_folder
      - DEFAULT_FILE_SOURCE=/data/uploads
    depends_on:
      - mqtt
      - sftp
    volumes:
      - ./upload_folder:/data/uploads
    ports:
      - "8083:8080" # Optional für Web-/API-Endpoints
    restart: no
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mqtt:
    container_name: mqtt-dev
    image: eclipse-mosquitto
    ports:
      - "1886:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    environment:
      - MQTT_ALLOW_ANONYMOUS=false
      - MQTT_USERNAME=admin
      - MQTT_PASSWORD=secret
    restart: unless-stopped

  sftp:
    container_name: sftp-dev
    image: atmoz/sftp
    ports:
      - "2222:22"
    volumes:
      - ./upload_folder:/home/test/uploads
      - ./sftp_readonly:/home/test/readonly:ro
      - ./sftp_writeonly:/home/test/writeonly
      - ./sshkeys:/home/test/.ssh/keys:ro
      - ./logs:/var/log/sftp
    environment:
      - SFTP_USERS=test:test:1001:1001:/uploads,user2:password:1002:1002:/shared/uploads
      - SFTP_LOG_LEVEL=DEBUG
    restart: unless-stopped

volumes:
  mosquitto_data:
  mosquitto_log:
  sftp_data:
  sftp_readonly:
  sftp_writeonly:
